<?php

namespace app\admin\controller;

use think\Controller;
use think\Session;

class Base extends Controller
{
   protected function _initialize()
   {
       parent::_initialize(); // TODO: Change the autogenerated stub
       define('USER_ID',Session::get('user_id'));
   }
   protected function isLogin(){
       if (empty(USER_ID)){
           $this->error('用户未登录，无权访问',url('user/login'));
       }
   }

   protected function alreadyLogin(){
       if (empty(!USER_ID)){
        $this->error('用户已经登录，请勿重复登录',url('index/index'));
       }
   }
}
